feat(DMVP-1712): have some fixes/changes to trigger new version generation by semantic release

diff --git a/githooks/commit-msg b/githooks/commit-msg
--- a/githooks/commit-msg
+++ b/githooks/commit-msg
@@ -1,86 +1,20 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# File generated by pre-commit: https://pre-commit.com
+# ID: 138fd403232d2ddd5efb44317e38bf03
 
-RED='\033[1;31m'
-YELLOW='\033[1;33m'
-GREEN='\033[1;32m'
-NC='\033[0m'
+# start templated
+INSTALL_PYTHON=/usr/bin/python3
+ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=commit-msg)
+# end templated
 
-isNvmOk=false
-isYarnOk=false
-isNodeOk=false
-isGccOk=false
+HERE="$(cd "$(dirname "$0")" && pwd)"
+ARGS+=(--hook-dir "$HERE" -- "$@")
 
-source ~/.nvm/nvm.sh > /dev/null 2>&1
-nvm -v > /dev/null 2>&1
-if [ ! $? -eq 0 ]; then
-  mkdir ~/.nvm > /dev/null 2>&1
-  (curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash) > /dev/null 2>&1
-
-  source ~/.nvm/nvm.sh
-
-  if [ `command -v nvm` ]; then
-      isNvmOk=true
-      #echo -e "$${GREEN}[ OK ]$${NC} nvm installed successfully"
-  else
-      isNvmOk=false
-      #echo -e "$${RED}[ FAIL ]$${NC} Error during nvm installation"
-  fi
-fi
-
-
-if  [  `command -v node`  ]; then
-    isNodeOk=true
-    #echo -e "$${GREEN}[ OK ]$${NC} npm and node is already installed"
+if [ -x "$INSTALL_PYTHON" ]; then
+    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
+elif command -v pre-commit > /dev/null; then
+    exec pre-commit "${ARGS[@]}"
 else
-  #echo -e "$${YELLOW}[ WAIT ]$${NC} npm is not installed.. installing"
-  nvm install node > /dev/null 2>&1
-  if [ `command -v node` ] && [ `command -v npm` ]; then
-      isNodeOk=true
-      #echo -e "$${GREEN}[ OK ]$${NC} npm installed successfully"
-  fi
-
-#  mkdir ~/.npm-global > /dev/null 2>&1
-#  npm config set prefix '~/.npm-global' > /dev/null 2>&1
-#  export PATH=~/.npm-global/bin:$PATH > /dev/null 2>&1
-#  source ~/.profile > /dev/null 2>&1
-
-fi
-
-
-if [ `command -v yarn` ]; then
-  isYarnOk=true
-  #echo -e "$${GREEN}[ OK ]$${NC} Yarn already installed"
-
-else
-  rm -rf ~/.yarn
-  (curl -o- -L https://yarnpkg.com/install.sh | bash) > /dev/null 2>&1
-  export PATH="$HOME/.yarn/bin:$PATH"
-  yarn config set prefix ~/.yarn -g > /dev/null 2>&1
-
-  if [ `command -v yarn` ]; then
-    isYarnOk=true
-     # echo $yarn_result
-    #  echo -e "$${GREEN}[ OK ]$${NC} Yarn installed successfully"
-  fi
-fi
-
-#echo -e "$${GREEN}[ OK ]$${NC}" nvm cache clear --force
-
-PATH="/c/Program Files/nodejs:$HOME/AppData/Roaming/npm/:$PATH"
-
-npm install --global git-conventional-commits > /dev/null 2>&1
-if [ $? -eq 0 ]; then
-    isGccOk=true
-   # echo -e "$${GREEN}[ OK ]$${NC} git-conventional-commit successfully installed"
-  else
-    isGccOk=false
-   # echo -e "$${RED}[ FAIL ]$${NC} Error during installation of git-conventional-commit"
-fi
-
-git-conventional-commits commit-msg-hook "$1"
-
-if [[ $isNodeOk && $isYarnOk && $isNvmOk && $isNodeOk ]]; then
-    echo -e "$${GREEN}[ OK ]$${NC} Dependencies installed successfully"
-else
-    echo -e "$${RED}[ FAIL ]$${NC} Error during dependency installation"
+    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
+    exit 1
 fi
